import '../styles/globals.css'
import '../styles/globals.scss'
import type { Metadata } from 'next'
import { Inter, Plus_Jakarta_Sans } from 'next/font/google'
import { ReactQueryClientProvider } from './react-query-provider'
import { Providers } from './providers';
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

// const plusJakarta = Plus_Jakarta_Sans({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700", "800"],
//   variable: "--font-jakarta",
// });

export const metadata: Metadata = {
  title: 'Listeck',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <ReactQueryClientProvider>
          <Providers>
            {children}
          </Providers>
        </ReactQueryClientProvider>
      </body>
    </html>
  )
}
