export const en = {
    shoppingList: 'Shopping List',
    addItem: 'Add Item',
    delete: 'Delete',
    edit: 'Edit',
    save: 'Save',
    failedToLoadItemsPleaseTryAgain: 'Failed to load items. Please try again.',
    noItemsYet: 'No items yet',
    yourListIsReadyAndWaitingAddYourFirstItemToGetStarted: 'Your list is ready and waiting. Add your first item to get started!',
    addProducts: 'Add Products',
    noItemsMatchYourSearch: 'No items match your search.',
    unchecked: 'Unchecked',
    checked: 'Checked',
    total: 'Total',
    other: 'Other',
    yourShoppingLists: 'Your shopping lists',
    logOut: 'Log out',
    failedToLoadLists: 'Failed to load lists',
    pleaseTryAgain: 'Please try again',
    noListsYet: 'No lists yet',
    createYourFirstListToGetStarted: 'Create your first list to get started',
    shareList: 'Share List',
    closeModal: 'Close modal',
    enterEmailAddress: 'Enter email address',
    invite: 'Invite',
    copyLink: 'Copy Link',
    whatsApp: 'WhatsApp',
    pleaseEnterAnEmailAddress: 'Please enter an email address',
    pleaseEnterAValidEmailAddress: 'Please enter a valid email address',
    checkOutThisList: 'Check out this list: ',
    createAccount: 'Create Account',
    welcomeBack: 'Welcome Back',
    signUpToGetStartedWithProductivityHub: 'Sign up to get started with ProductivityHub',
    signInToContinueToYourDashboard: 'Sign in to continue to your dashboard',
    emailAddress: 'Email Address',
    enterYourEmail: 'Enter your email',
    password: 'Password',
    enterYourPassword: 'Enter your password',
    signIn: 'Sign In',
    orContinueWith: 'or continue with',
    continueWithGoogle: 'Continue with Google',
    alreadyHaveAnAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    signUp: 'Sign Up',
    signInToSmarterShopping: 'Sign In to Smarter Shopping',
    trackTasksManageTimeAndAchieveYourGoalsWithOurIntuitiveDashboardDesignedForModernProfessionals: 'Track tasks, manage time, and achieve your goals with our intuitive dashboard designed for modern professionals.',
    manageYourLists: 'Manage Your Lists',
    trackYourExpenses: 'Track Your Expenses',
    shopSmarter: 'Shop Smarter',
    emailIsRequired: 'Email is required',
    passwordIsRequired: 'Password is required',
    passwordMustBeAtLeast6CharactersLong: 'Password must be at least 6 characters long',
    egMilk: 'e.g. milk',
    clearInput: 'Clear input',
    speechToText: 'Speech to text',
    popular: 'Popular',
    recent: 'Recent',
    decreaseQuantity: 'Decrease quantity',
    removeItem: 'Remove item',
    noRecentItemsYet: 'No recent items yet',
    renameList: 'Rename List',
    enterListName: 'Enter list name',
    cancel: 'Cancel',
    rename: 'Rename',
    createList: 'Create List',
    deleteList: 'Delete List?',
    areYouSureYouWantToDelete: 'Are you sure you want to delete',
    thisActionCannotBeUndone: 'This action cannot be undone.',
    createNewList: 'Create new list',
    closeDrawer: 'Close drawer',
    name: 'Name',
    enterItemName: 'Enter item name',
    category: 'Category',
    quantity: 'Quantity',
    unit: 'Unit',
    price: 'Price',
    description: 'Description',
    addNotesOrDetails: 'Add notes or details...',
    deleteItem: 'Delete Item',
    done: 'Done',
    searchItems: 'Search items...',
    closeSearch: 'Close search',
    search: 'Search',
    share: 'Share',
    menu: 'Menu',
    sortBy: 'Sort by',
    aZ: 'A-Z',
    uncheckAll: 'Uncheck all',
    openMenu: 'Open menu',
    copy: 'Copy',
    loading: 'Loading',
    preparingYourLists: 'Preparing your lists...',
    language: 'Language',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    logout: 'Logout',
    english: 'English',
    spanish: 'Español',
    french: 'Français',
    german: 'Deutsch',
    clickMeBiatch: 'Click Me Biatch'
};