export const he = {
    shoppingList: 'רשימת קניות',
    addItem: 'הוסף פריט',
    delete: 'מחק',
    edit: 'ערוך',
    save: 'שמור',
    failedToLoadItemsPleaseTryAgain: 'טעינת פריטים נכשלה. אנא נסה שוב.',
    noItemsYet: 'אין פריטים עדיין',
    yourListIsReadyAndWaitingAddYourFirstItemToGetStarted: 'הרשימה שלך מוכנה ומחכה. הוסף את הפריט הראשון שלך כדי להתחיל!',
    addProducts: 'הוסף מוצרים',
    noItemsMatchYourSearch: 'אין פריטים התואמים לחיפוש שלך.',
    unchecked: 'לא סומן',
    checked: 'סומן',
    total: 'סה"כ',
    vegetables: 'ירקות',
    fruits: 'פירות',
    dairy: 'מוצרי חלב',
    meat: 'בשר',
    frozen: 'קפואים',
    fish: 'דגים',
    bakery: 'מאפים',
    beverages: 'משקאות',
    alcohol: 'אלכוהול',
    snacks: 'חטיפים',
    cleaning: 'ניקיון',
    pets: 'חיות מחמד',
    electronics: 'אלקטרוניקה',
    health: 'בריאות',
    clothing: 'ביגוד',
    baby: 'תינוקות',
    dry: 'מוצרים יבשים',
    other: 'אחר',
    yourShoppingLists: 'הרשימות שלי',
    logOut: 'התנתק',
    failedToLoadLists: 'טעינת רשימות נכשלה',
    pleaseTryAgain: 'אנא נסה שוב',
    noListsYet: 'אין רשימות עדיין',
    createYourFirstListToGetStarted: 'צור את הרשימה הראשונה שלך כדי להתחיל',
    shareList: 'שתף רשימה',
    closeModal: 'סגור חלון',
    enterEmailAddress: 'הכנס כתובת אימייל',
    invite: 'הזמן',
    copyLink: 'העתק קישור',
    whatsApp: 'וואטסאפ',
    pleaseEnterAnEmailAddress: 'אנא הזן כתובת אימייל',
    pleaseEnterAValidEmailAddress: 'אנא הזן כתובת אימייל תקפה',
    checkOutThisList: 'בדוק את הרשימה הזו: ',
    createAccount: 'צור חשבון',
    welcomeBack: 'ברוך הבא',
    signUpToGetStartedWithProductivityHub: 'הירשם כדי להתחיל עם Listeck',
    popularItems: 'מוצרים פופולריים',
    signInToContinueToYourDashboard: 'היכנס כדי להמשיך לרשימות שלך',
    emailAddress: 'כתובת אימייל',
    enterYourEmail: 'הכנס את האימייל שלך',
    password: 'סיסמה',
    enterYourPassword: 'הכנס את הסיסמה שלך',
    signIn: 'התחבר',
    orContinueWith: 'או המשך עם',
    continueWithGoogle: 'המשך עם גוגל',
    alreadyHaveAnAccount: 'כבר יש לך חשבון?',
    dontHaveAccount: "אין לך חשבון?",
    signUp: 'הירשם',
    signInToSmarterShopping: 'רשימת הקניות שלך, במהירות הדיבור.',
    authSecondaryText: 'ארגנו את רשימות הקניות שלכם תוך שניות, שתפו עם משפחה וחברים והוסיפו פריטים באמצעות קול - לגמרי בחינם',
    manageYourLists: 'נהל את הרשימות שלך',
    trackYourExpenses: 'עקוב אחר ההוצאות שלך',
    shopSmarter: 'קנה חכם יותר',
    emailIsRequired: 'אימייל נדרש',
    passwordIsRequired: 'סיסמה נדרשת',
    passwordMustBeAtLeast6CharactersLong: 'הסיסמה חייבת להיות באורך 6 תווים לפחות',
    egMilk: 'לדוגמה חלב',
    clearInput: 'נקה קלט',
    speechToText: 'דיבור לטקסט',
    popular: 'פופולרי',
    recent: 'אחרונים',
    decreaseQuantity: 'הפחת כמות',
    removeItem: 'הסר פריט',
    noRecentItemsYet: 'אין פריטים אחרונים עדיין',
    renameList: 'שנה שם רשימה',
    enterListName: 'הכנס שם רשימה',
    cancel: 'בטל',
    rename: 'שנה שם',
    createList: 'צור רשימה',
    deleteList: 'מחק רשימה',
    areYouSureYouWantToDelete: 'האם אתה בטוח שברצונך למחוק',
    thisActionCannotBeUndone: 'פעולה זו בלתי הפיכה.',
    createNewList: 'צור רשימה חדשה',
    closeDrawer: 'סגור מגירה',
    name: 'שם',
    enterItemName: 'הכנס שם פריט',
    category: 'קטגוריה',
    quantity: 'כמות',
    unit: 'יחידה',
    price: 'מחיר',
    description: 'תיאור',
    addNotesOrDetails: 'הוסף הערות או פרטים',
    deleteItem: 'מחק פריט',
    done: 'בוצע',
    searchItems: 'חפש פריטים...',
    closeSearch: 'סגור חיפוש',
    search: 'חפש',
    share: 'שתף',
    menu: 'תפריט',
    sortBy: 'מיין לפי',
    aZ: 'א-ת',
    uncheckAll: 'בטל סימון הכל',
    openMenu: 'פתח תפריט',
    copy: 'העתק',
    loading: 'טוען',
    preparingYourLists: 'מכין את הרשימות שלך...',
    language: 'שפה',
    privacyPolicy: 'מדיניות פרטיות',
    termsOfService: 'תנאי שירות',
    logout: 'התנתק',
    english: 'אנגלית',
    spanish: 'ספרדית',
    french: 'צרפתית',
    german: 'גרמנית',
    addVoiceItemsTitle: 'להוסיף פריטים מהקלטה?',
    addSelected: 'הוסף נבחרים',
    loginForNow: 'התחבר',
    voiceRecordingTitle: '...מאזין',
    voiceRecordingSubtitle: 'רשום את הפריטים שלך, מופרדים ב ״ו״',
    stopRecording: 'הפסק הקלטה',
    confirmVoiceItemsTitle: '?להוסיף את הפריטים האלה',
    confirm: 'אשר',
    title: 'Productive',
    userMenu: 'תפריט משתמש',
    // Landing page - Hero Section
    shoppingListsSimplified: 'רשימת קניות',
    fast: 'במהירות',
    heroDescription: 'צור, ארגן ושתף רשימות קניות תוך שניות. עולם לא תשכח פריט שוב עם תזכורות חכמות ושיתוף פעולה נוח.',
    startForFree: 'התחל בחינם',
    weeklyGroceries: 'קניות שבועיות',
    itemsShared: 'פריטים · משותף עם',
    produce: 'מוצרי טרי',
    pantry: 'מpantaka',
    organic: 'אורגני',
    // Landing page - Features Section
    features: 'תכונות',
    everythingYouNeedForSmarterShopping: 'כל מה שאתה צריך לקניות חכמות יותר',
    fromSmartCategorizationToRealTimeCollaboration: 'מ categorization חכם לשיתוף פעולה בזמן אמת, ListFlow הופך את ניהול הקניות שלך לבלא מאמץ.',
    smartCategorization: 'Categorization חכם',
    itemsAutomaticallySorted: 'פריטים מסוווגים באופן אוטומטי לקטגוריות כמו מוצרי טרי, חלב וחנויה — אין צורך בארגון ידני.',
    sharedLists: 'רשימות משותפות',
    collaborateInRealTime: 'הזמן בני משפחה או כולי דירה לשתוף פעולה על רשימות בזמן אמת. ראה עדכונים מיד.',
    smartReminders: '100% חינם',
    gentleNudgesWhenNear: 'חינם. ללא עמלות נסתרות, ללא שכבות פרימיום, ללא טריקים. הכל כלול.',

    worksEverywhere: 'פועל בכל מקום',
    accessYourLists: 'גש לרשימות שלך בכל מכשיר — טלפון, טאבלט או שולחן עבודה. הכל מסתנכרן בצורה חלקה.',
    priceTracking: 'עקיבות אחר מחירים',
    keepAnEyeOnSpending: 'עקוב אחר ההוצאות שלך באמצעות הערכות מחיר משולבות וייעוד תקציב לכל רשימה.',
    privateAndSecure: 'פרטי וביטוח',
    dataIsEncrypted: 'הנתונים שלך מוצפנים ולעולם לא משותפים. אנחנו משוכנעים שרשימת הקניות שלך אינה עסק של אף אחד אחר.',
    // Landing page - How It Works Section
    howItWorks: 'איך זה עובד',
    threeStepsToOrganizedShopping: 'שלוש צעדים לקניות מאורגנות',
    noCredCardRequired: 'ההתחלה לוקחת פחות מ 30 שניות. לא נדרשת כרטיס אשראי.',
    createAList: 'צור רשימה',
    nameYourListAndChooseCategory: 'תן שם לרשימה שלך ובחר קטגוריה — מכולת, פריטים ליתיים או סוג מותאם אישית.',
    addItems: 'הוסף פריטים',
    typeOrVoiceAddItems: 'הקלד או הוסף קול פריטים. ה AI שלנו מציע פריטים בהתאם להיסטוריית הקניות והעדפות שלך.',
    shareAndShop: 'שתף ו קנה',
    shareWithFamilyAndFriends: 'שתף עם משפחה או חברים, סמן פריטים בזמן אמת, ותמיד אל תקנה שוב.',
    // Navigation
    home: 'בית',
    getStarted: 'התחל',
    hebrew: 'עברית'
};