export const he = {
    shoppingList: 'רשימת קניות',
    addItem: 'הוסף פריט',
    delete: 'מחק',
    edit: 'ערוך',
    save: 'שמור',
    failedToLoadItemsPleaseTryAgain: 'טעינת פריטים נכשלה. אנא נסה שוב.',
    noItemsYet: 'אין פריטים עדיין',
    yourListIsReadyAndWaitingAddYourFirstItemToGetStarted: 'הרשימה שלך מוכנה ומחכה. הוסף את הפריט הראשון שלך כדי להתחיל!',
    addProducts: 'הוסף מוצרים',
    noItemsMatchYourSearch: 'אין פריטים התואמים לחיפוש שלך.',
    unchecked: 'לא סומן',
    checked: 'סומן',
    total: 'סה"כ',
    vegetables: 'ירקות',
    fruits: 'פירות',
    dairy: 'מוצרי חלב',
    meat: 'בשר',
    frozen: 'קפואים',
    fish: 'דגים',
    bakery: 'מאפים',
    beverages: 'משקאות',
    alcohol: 'אלכוהול',
    snacks: 'חטיפים',
    cleaning: 'ניקיון',
    pets: 'חיות מחמד',
    electronics: 'אלקטרוניקה',
    health: 'בריאות',
    clothing: 'ביגוד',
    baby: 'תינוקות',
    other: 'אחר',
    yourShoppingLists: 'רשימות הקניות שלך',
    logOut: 'התנתק',
    failedToLoadLists: 'טעינת רשימות נכשלה',
    pleaseTryAgain: 'אנא נסה שוב',
    noListsYet: 'אין רשימות עדיין',
    createYourFirstListToGetStarted: 'צור את הרשימה הראשונה שלך כדי להתחיל',
    shareList: 'שתף רשימה',
    closeModal: 'סגור חלון',
    enterEmailAddress: 'הכנס כתובת אימייל',
    invite: 'הזמן',
    copyLink: 'העתק קישור',
    whatsApp: 'וואטסאפ',
    pleaseEnterAnEmailAddress: 'אנא הזן כתובת אימייל',
    pleaseEnterAValidEmailAddress: 'אנא הזן כתובת אימייל תקפה',
    checkOutThisList: 'בדוק את הרשימה הזו: ',
    createAccount: 'צור חשבון',
    welcomeBack: 'ברוך הבא',
    signUpToGetStartedWithProductivityHub: 'הירשם כדי להתחיל עם ProductivityHub',
    signInToContinueToYourDashboard: 'היכנס כדי להמשיך ללוח המחוונים שלך',
    emailAddress: 'כתובת אימייל',
    enterYourEmail: 'הכנס את האימייל שלך',
    password: 'סיסמה',
    enterYourPassword: 'הכנס את הסיסמה שלך',
    signIn: 'התחבר',
    orContinueWith: 'או המשך עם',
    continueWithGoogle: 'המשך עם גוגל',
    alreadyHaveAnAccount: 'כבר יש לך חשבון?',
    dontHaveAccount: "אין לך חשבון?",
    signUp: 'הירשם',
    signInToSmarterShopping: 'התחבר לקניות חכמות יותר',
    trackTasksManageTimeAndAchieveYourGoalsWithOurIntuitiveDashboardDesignedForModernProfessionals: 'עקוב אחר משימות, נהל זמן והשג את מטרותיך באמצעות לוח המחוונים האינטואיטיבי שלנו המיועד לאנשי מקצוע מודרניים.',
    manageYourLists: 'נהל את הרשימות שלך',
    trackYourExpenses: 'עקוב אחר ההוצאות שלך',
    shopSmarter: 'קנה חכם יותר',
    emailIsRequired: 'אימייל נדרש',
    passwordIsRequired: 'סיסמה נדרשת',
    passwordMustBeAtLeast6CharactersLong: 'הסיסמה חייבת להיות באורך 6 תווים לפחות',
    egMilk: 'לדוגמה חלב',
    clearInput: 'נקה קלט',
    speechToText: 'דיבור לטקסט',
    popular: 'פופולרי',
    recent: 'אחרונים',
    decreaseQuantity: 'הפחת כמות',
    removeItem: 'הסר פריט',
    noRecentItemsYet: 'אין פריטים אחרונים עדיין',
    renameList: 'שנה שם רשימה',
    enterListName: 'הכנס שם רשימה',
    cancel: 'בטל',
    rename: 'שנה שם',
    createList: 'צור רשימה',
    deleteList: 'מחק רשימה',
    areYouSureYouWantToDelete: 'האם אתה בטוח שברצונך למחוק',
    thisActionCannotBeUndone: 'פעולה זו בלתי הפיכה.',
    createNewList: 'צור רשימה חדשה',
    closeDrawer: 'סגור מגירה',
    name: 'שם',
    enterItemName: 'הכנס שם פריט',
    category: 'קטגוריה',
    quantity: 'כמות',
    unit: 'יחידה',
    price: 'מחיר',
    description: 'תיאור',
    addNotesOrDetails: 'הוסף הערות או פרטים',
    deleteItem: 'מחק פריט',
    done: 'בוצע',
    searchItems: 'חפש פריטים...',
    closeSearch: 'סגור חיפוש',
    search: 'חפש',
    share: 'שתף',
    menu: 'תפריט',
    sortBy: 'מיין לפי',
    aZ: 'א-ת',
    uncheckAll: 'בטל סימון הכל',
    openMenu: 'פתח תפריט',
    copy: 'העתק',
    loading: 'טוען',
    preparingYourLists: 'מכין את הרשימות שלך...',
    language: 'שפה',
    privacyPolicy: 'מדיניות פרטיות',
    termsOfService: 'תנאי שירות',
    logout: 'התנתק',
    english: 'אנגלית',
    spanish: 'ספרדית',
    french: 'צרפתית',
    german: 'גרמנית',
    addVoiceItemsTitle: 'להוסיף פריטים מהקלטה?',
    addSelected: 'הוסף נבחרים',
    loginForNow: 'התחבר',
    voiceRecordingTitle: '...מאזין',
    voiceRecordingSubtitle: 'רשום את הפריטים שלך, מופרדים ב ״ו״',
    stopRecording: 'הפסק הקלטה',
    confirmVoiceItemsTitle: '?להוסיף את הפריטים האלה',
    confirm: 'אשר',
    title: 'Productive',
    userMenu: 'תפריט משתמש'
};