import '../../styles/globals.css'
import '../../styles/globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SidebarWrapper } from '@/components/Sidebar/SidebarWrapper'
import { Providers } from '../providers'
import { ReactQueryClientProvider } from '../react-query-provider'
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <ReactQueryClientProvider>
          <Providers>
            <SidebarWrapper />
            {children}
          </Providers>
        </ReactQueryClientProvider>
      </body>
    </html>
  )
}
